

CREATE TABLE PRODUCT_CATALOG (

	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	product_name VARCHAR(50) NOT NULL,
	product_type VARCHAR(50) NOT NULL,
	product_description VARCHAR(100),
	created_on TIMESTAMP NOT NULL,
	created_by VARCHAR(50) NOT NULL,
	updated_on TIMESTAMP NOT NULL,
	updated_by VARCHAR(50) NOT NULL
);

CREATE INDEX IDX_PRODUCT_NAME ON PRODUCT_CATALOG (product_name);